startup:
  groups:
    - default
projects:
  glue:
    command:
      cmd:
        compiler: cd dev/glue && yarn install && yarn run dev
        definitions: cd dev/glued && yarn install && yarn run dev
        rpcclient: cd dev/gluedrpcclient && yarn install && yarn run dev
        rpcserver: cd dev/gluedrpcserver && yarn install && yarn run dev
        files: cd dev/gluedfiles && yarn install && yarn run dev
  glueddb:
    command:
      cmd:
        server: cd dev/glueddb && yarn install && yarn run dev
        postgres: cd dev/glueddb && docker-compose rm -f && docker-compose up
  gluedui:
    command:
      workdir: dev/gluedui
      cmd:
        server: cd dev/gluedui && yarn install && yarn run start
  sbox:
    command:
      workdir: dev/sbox
      cmd:
        main: cd dev/sbox &&  yarn install && yarn run dev

  # These are sacrificial bootstrap nodes
  keystoneconsul:
    command:
      cmd:
        1: "cd dev/keystone/consul && ../../glue/files/hostd/consul agent -server -data-dir ./data/consul1 -bind 127.128.32.2 -bootstrap-expect 3"
        2: "cd dev/keystone/consul && ../../glue/files/hostd/consul agent -data-dir ./data/consul2 -bind 127.128.32.3 -retry-join 10.127.32.2"
        3: "cd dev/keystone/consul && ../../glue/files/hostd/consul agent -data-dir ./data/consul3 -bind 127.128.32.4 -retry-join 10.127.32.2"
groups:
  default:
    projects:
      - glue
      - glueddb
      - gluedui
      - keystoneconsul
      # - sbox