startup:
  groups:
    - default
projects:
  glue:
    command:
      workdir: dev/glue
      cmd: yarn install && yarn run dev
  glued:
    command:
      workdir: dev/glued
      cmd: yarn install && yarn run dev
  glueddb:
    command:
      workdir: dev/glueddb
      cmd: yarn install && yarn run dev
  glueddbpostgres:
    command:
      workdir: dev/glueddb
      cmd: docker-compose rm -f && docker-compose up
  gluedfiles:
    command:
      workdir: dev/gluedfiles
      cmd: yarn install && yarn run dev
  gluedrpcclient:
    command:
      workdir: dev/gluedrpcclient
      cmd: yarn run dev
  gluedrpcserver:
    command:
      workdir: dev/gluedrpcserver
      cmd: yarn install && yarn run dev
  gluedui:
    command:
      workdir: dev/gluedui
      cmd: yarn install && yarn run start
  sbox:
    commandi:
      workdir: dev/sbox
      cmd: yarn install && yarn run dev
groups:
  default:
    projects:
      - glue
      - glued
      - gluedrpcserver
      - gluedrpcclient
      - glueddb
      - glueddbpostgres
      - gluedfiles
      - gluedui
      - sbox