version: "3.6"
services:
  db:
    image: postgres:13.1-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
    volumes:
      - "./pg:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:6
    environment:
      PGADMIN_DEFAULT_EMAIL: "db@db.localhost"
      PGADMIN_DEFAULT_PASSWORD: "db"
    ports:
      - "8082:80"
    volumes:
      - "./pgadmin4/servers.json:/pgadmin4/servers.json"
    restart: unless-stopped
    depends_on:
      - db
    logging:
      driver: none